#!/usr/bin/env bash
# transfer file to server
if [ $# -ge 4 ]
then
	scp -i "$4" -o StrictHostKeyChecking=no "$3"@"$2":"~/$1"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
