#!/usr/bin/env bash
# 4-not_found_page_404
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" > var/www/html/404.html
string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-enabled/default

service nginx restart
