#!/usr/bin/env bash
#change local host and facebook ip
cp /etc/hosts ~/hosts.new
sed -i "s/^127\.0\.0\.1/127\.0\.0\.2 localhost/" ~/hosts.new
sed -i 's/^.*facebook.com/8.8.8.8 facebook.com/' ~/hosts.new
sudo cp ~/hosts.new /etc/hosts
